apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskScheduler.fullname" . }}-db
  labels:
    {{- include "taskScheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.config.springDatasourcePassword | quote }}
